name: test-dispatch

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      confirm_apply:
        description: "Type APPLY to confirm"
        required: true
        default: "NO"

jobs:
  hello:
    runs-on: [self-hosted]
    steps:
      - run: echo "Hello â€” confirm_apply=${{ github.event.inputs.confirm_apply }}"
